apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: bwangel/kubia:v0.4
          ports:
            - containerPort: 8080
              protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: k8s-node2

