apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubia
  name: kubia-svc
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubia
  sessionAffinity: None
  type: NodePort

