apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
spec:
  volumes:
  - name: content
    emptyDir: {}
  containers:
  - name: html-generator
    image: bwangel/fortune:env
    env:
    - name: INTERNAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    volumeMounts:
    - name: content
      mountPath: /var/htdocs
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - name: http
      containerPort: 80
