# 利用 configmap 卷来设置配置文件
apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-volume
spec:
  volumes:
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: fortune-config
      # 设置挂载文件的默认权限
      defaultMode: 0600
      # 指定只挂载一个文件
      items:
      - key: my-nginx-config.conf
        path: gzip.conf
  containers:
  - name: html-generator
    image: bwangel/fortune:env
    env:
    - name: INTERNAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - name: web-server
    image: nginx:alpine
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: config
      mountPath: /tmp/whole-fortune-config-volumne
      readOnly: true
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
