apiVersion: apps/v1
kind: Deployment
metadata:
  name: peach-app
  namespace: qae
  labels:
    app: peach
spec:
  replicas: 1
  template:
    metadata:
      name: peach-app
      labels:
        app: peach
    spec:
      containers:
        - name: peach-app
          image: hashicorp/http-echo
          args:
            - "-text=peach"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: peach

---

kind: Service
apiVersion: v1
metadata:
  name: peach-service
  namespace: qae
spec:
  selector:
    app: peach
  ports:
    - targetPort: 5678
      port: 8000 # Default port for image