apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: bwangel/kubia:v0.1
      name: kubiame
      ports:
      - containerPort: 8080
        protocol: TCP
