apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubia
spec:
  serviceName: kubia
  replicas: 2
  template:
    metadata:
      labels:
        app: kubia_stateful
    spec:
      containers:
        - name: kubia
          image: bwangel/kubia-storage:v0.3
          command:
            - /go/bin/kubia
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /var/data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 5Mi
        accessModes:
          - ReadWriteOnce
  selector:
    matchLabels:
      app: kubia_stateful
