# -*- mode: ruby -*-
# vi: set ft=ruby :

# Verify whether required plugins are installed.
required_plugins = [ "vagrant-disksize" ]
required_plugins.each do |plugin|
  if not Vagrant.has_plugin?(plugin)
    raise "The vagrant plugin #{plugin} is required. Please run `vagrant plugin install #{plugin}`"
  end
end

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  # You need install plugin vagrant-disksize on vagrant.
  # For this, do vagrant plugin install vagrant-disksize.
  config.disksize.size = "30GB"

  $num_instances = 3
  $etcd_cluster = "node1=http://172.17.9.101:2380"
  (1..$num_instances).each do |i|
    config.vm.define "k8s-node#{i}" do |node|
      node.vm.box = "ubuntu/bionic"
      node.vm.hostname = "k8s-node#{i}"
      ip1 = "172.17.9.#{i+100}"
      ip2 = "172.16.0.#{i+100}"
      ip3 = "172.15.0.#{i+100}"
      node.vm.network "private_network", ip: ip1, netmask: "16"
      node.vm.network "private_network", ip: ip2, netmask: "16"
      node.vm.network "private_network", ip: ip3, netmask: "16"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 2
        vb.name = "k8s-node#{i}"
      end
      # node.vm.provision "shell", path: "install.sh", args: [i]
    end
  end
end
