# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  $num_instances = 3
  $etcd_cluster = "node1=http://172.17.9.101:2380"
  (1..$num_instances).each do |i|
    config.vm.define "k8s-node#{i}" do |node|
      node.vm.box = "ubuntu/bionic"
      node.vm.hostname = "k8s-node#{i}"
      ip = "172.17.9.#{i+100}"
      node.vm.network "private_network", ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.name = "k8s-node#{i}"
      end
      node.vm.provision "shell", path: "install.sh", args: [i, ip, $etcd_cluster]
    end
  end
end
